---
title: "Social Responsibility and Data Science"
author: "Saghir Bashir & Andreia Carlos"
date: "10th December 2018"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: [default, robot-fonts]
    self_contained: true
    # lib_dir: libs
    # https://github.com/gnab/remark/wiki/Configuration
    nature:
      ratio: 16:9
      highlightStyle: default
      highlightLanguage: r
      highlightLines: true
      highlightSpans: false
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
    seal: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(xaringan)
```

class: inverse, middle, center

# Social Responsibility <br>and Data Science

<br>

### Saghir Bashir & Andreia Carlos

---
class: middle, center

# We are Living in the 

# Information Age

---
class: middle, center

# Data Driven Decisions

# Targeted Goods and Services


---
class: middle, center

# Data Opportunities

# Data Risks

---
class: inverse, middle, center

# We are Living in the 

# Mis-information Age

---
class: middle, center

# Legislation Catching Up (GDPR)

# Many Gaps Remain

# Consumers Demanding More


---
class: middle, center

# Honesty

# Accuracy 

# Reliability

# Transparency


---
class: inverse middle, center

# Socially Responsible Data Science

<br>

# Accountability 

# Trustworthiness


---
class: inverse, middle, center

# Social Inclusion 

# and Data Science

---
class: middle, center

# Opportunities

# Higher Quality Data

# Minimum But Valuable Data

---
class: middle, center

# Leverage Resources

# Homeless

# Disadvantaged Groups

---
class: middle, center

# Future Investment

# Data Skills

# Data Education

# Data Vision

---
class: middle, center

# Future Today

# Girls & Minorities

# Deprived Communities

# Knowledge Sharing


---
class: inverse, middle, center

# Organisational Social Responsibilty 

# MUST

# Extend to Data and Data Science
